@echo off
:: Subroutine of gobackup.bat
:: For Making a random password of a various length
:: by <https://github.com/GrantAccess/Janis-Verona/> (CC)
:: the author has not changed this document since Sunday 16 Jan 2022

:: length of the word 9-20
:: if a password is compromised, attacker will assume all words are same length
SET /A LENNY=0
SET /A LENMIN=9
SET /A LENMAX=20
SET /A LENDIF=%LENMAX%-%LENMIN%
:: pick a number, in the differance range, plus the smallest number
SET /A LENNY=%RANDOM%%%%LENDIF%+%LENMIN%
:: echo %LENDIF%
:: echo %LENNY%
set love=

:: for as many times as the word length pick a letter
SET /A tally=0
:pickle
SET /A tally=%tally%+1
SET love=%LUCK%

:: pick a number
SET /A RANSID=%RANDOM%%%59+1
:: echo %RANSID%

:: turn the number into a letter
IF %RANSID% EQU 1 SET LTR=a
IF %RANSID% EQU 2 SET LTR=b
IF %RANSID% EQU 3 SET LTR=c
IF %RANSID% EQU 4 SET LTR=d
IF %RANSID% EQU 5 SET LTR=e
IF %RANSID% EQU 6 SET LTR=f
IF %RANSID% EQU 7 SET LTR=g
IF %RANSID% EQU 8 SET LTR=h
IF %RANSID% EQU 9 SET LTR=i
IF %RANSID% EQU 10 SET LTR=j
IF %RANSID% EQU 11 SET LTR=k
IF %RANSID% EQU 12 SET LTR=l
IF %RANSID% EQU 13 SET LTR=m
IF %RANSID% EQU 14 SET LTR=n
IF %RANSID% EQU 15 SET LTR=o
IF %RANSID% EQU 16 SET LTR=p
IF %RANSID% EQU 17 SET LTR=q
IF %RANSID% EQU 18 SET LTR=r
IF %RANSID% EQU 19 SET LTR=s
IF %RANSID% EQU 20 SET LTR=t
IF %RANSID% EQU 21 SET LTR=u
IF %RANSID% EQU 22 SET LTR=v
IF %RANSID% EQU 23 SET LTR=w
IF %RANSID% EQU 24 SET LTR=x
IF %RANSID% EQU 25 SET LTR=y
IF %RANSID% EQU 26 SET LTR=z
IF %RANSID% EQU 27 SET LTR=A
IF %RANSID% EQU 28 SET LTR=1
IF %RANSID% EQU 29 SET LTR=B
IF %RANSID% EQU 30 SET LTR=2
IF %RANSID% EQU 31 SET LTR=C
IF %RANSID% EQU 32 SET LTR=3
IF %RANSID% EQU 33 SET LTR=D
IF %RANSID% EQU 34 SET LTR=4
IF %RANSID% EQU 35 SET LTR=E
IF %RANSID% EQU 36 SET LTR=5
IF %RANSID% EQU 37 SET LTR=F
IF %RANSID% EQU 38 SET LTR=6
IF %RANSID% EQU 39 SET LTR=G
IF %RANSID% EQU 30 SET LTR=7
IF %RANSID% EQU 31 SET LTR=H
IF %RANSID% EQU 32 SET LTR=8
IF %RANSID% EQU 33 SET LTR=I
IF %RANSID% EQU 34 SET LTR=9
IF %RANSID% EQU 35 SET LTR=J
IF %RANSID% EQU 36 SET LTR=0
IF %RANSID% EQU 37 SET LTR=K
IF %RANSID% EQU 38 SET LTR=@
IF %RANSID% EQU 39 SET LTR=L
IF %RANSID% EQU 40 SET LTR=*
IF %RANSID% EQU 41 SET LTR=M
IF %RANSID% EQU 42 SET LTR=-
IF %RANSID% EQU 43 SET LTR=N
IF %RANSID% EQU 44 SET LTR=#
IF %RANSID% EQU 45 SET LTR=O
IF %RANSID% EQU 46 SET LTR=&
IF %RANSID% EQU 47 SET LTR=P
IF %RANSID% EQU 48 SET LTR=!
IF %RANSID% EQU 49 SET LTR=Q
IF %RANSID% EQU 50 SET LTR=$
IF %RANSID% EQU 51 SET LTR=R
IF %RANSID% EQU 52 SET LTR=W
IF %RANSID% EQU 53 SET LTR=S
IF %RANSID% EQU 54 SET LTR=X
IF %RANSID% EQU 55 SET LTR=T
IF %RANSID% EQU 56 SET LTR=Y
IF %RANSID% EQU 57 SET LTR=U
IF %RANSID% EQU 58 SET LTR=Z
IF %RANSID% EQU 59 SET LTR=V

:: echo %LTR%

:: the word is love
set love=%love%%LTR%
SET LUCK=%love%

:: is the word long enough?
:: if not, pick another
if %tally% LSS %LENNY% GOTO :pickle

echo %LENNY%
echo %love%

:: pause
